ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_1_url TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_1_alt TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_2_url TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_2_alt TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_3_url TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_3_alt TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS main_image_alt TEXT;
